### ISSUE TITLE
 Missing = inserted for \ifnum.

### ISSUE THREAD

**Issue by rfabbri** [cvpr-org/author-kit#12]
I get this error on Mac OS:

```
CVPR 8.5 x 11-Inch Proceedings Style `cvpr.sty'.
(/usr/local/texlive/2015/texmf-dist/tex/latex/lineno/lineno.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/enumitem/enumitem.sty))
! Missing = inserted for \ifnum.
<to be read again>
                   E
l.9
?
```

pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)

**Comment by taiya** [comment]
Hi there, 

I don't think we have enough info to help.
I am not getting any error under macOS with (or Overleaf):
```
(base) /Library/TeX/Distributions: pdflatex --version
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
kpathsea version 6.3.4
```

Which version of texlive are you using? (is it up to date?)
Are you using a pristine copy of the repo? (I am not going to debug your code)

**Comment by rfabbri** [comment]
> Are you using a pristine copy of the repo? 

yes

> Which version of texlive are you using? (is it up to date?)

The error occurs with an old version: 
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)

Updating it now works:
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
