### ISSUE TITLE
The `cite' package should not be used (natbib)	with natbib. Use option `sort' instead.

### ISSUE THREAD

**Issue by licongguan** [cvpr-org/author-kit#14]
The `cite' package should not be used
(natbib)	with natbib. Use option `sort' instead.

**Comment by licongguan** [comment]
I did not use the cite package, but I received this error message

**Comment by taiya** [comment]
Hi @cr333 want to take a look as you added natbib?

**Comment by zhazhiyuan** [comment]
While the template runs successfully on Overleaf, I have been experiencing consistent errors when trying to compile it locally on a Windows system. The error message is displayed as shown in the attached image. I consulted with other members of our lab who are also using Windows, and they reported encountering the same issue. However, when the template was tested on a Mac using TeXShop, it worked seamlessly.

Based on my observations, it seems that the current Latex template might not be fully compatible with Windows systems. I would appreciate it if you could kindly investigate this issue and possibly provide a resolution or guidance on how to work around it.  @cr333 

![Error](https://github.com/cvpr-org/author-kit/assets/23114731/2dacd8e1-9c6e-4b10-8e3e-0591f688555a)

**Comment by ShoufaChen** [comment]
> I did not use the cite package, but I received this error message

The `cite` package is imported in `cvpr.sty`.

**Comment by licongguan** [comment]
solved! ，Delete "**\RequirePackage{cite} % Automatically ordered citations**" in "**cvpr.sty**"
