### ISSUE TITLE
CVPR 24 latex template problem...

### ISSUE THREAD

**Issue by LWShowTime** [cvpr-org/author-kit#17]
When I start a new Section with:
`\section{Introduction}

AAA

BBB`

The compiled pdf will have indent before BBB but not indent before AAA. How can I solve this?

**Comment by rfabbri** [comment]
It is intentional. Don't worry about it.

**Comment by taiya** [comment]
you can always have explicit control with `\noindent`.

**Comment by adinriv** [comment]
> you can always have explicit control with `\noindent`.

The authors shouldn't do this, since it is intended to have indentation to signal new paragraphs, but there is none after the titles since it is clear where the paragraph begins.
