### ISSUE TITLE
Include xcolor in cvpr.sty

### ISSUE THREAD

**Issue by igkiou** [cvpr-org/author-kit#21]
I would suggest including `xcolor` inside `cvpr.sty`.

The current template:
1. loads `xcolor` inside the file `preamble.tex`; 
2. uses it inside `main.tex` to define a CVPR-specific color;
3. uses that color inside the recommended `hyperref` options.

Given that the `hyperref` options are meant as part of the official template recommendations, whereas `preamble.tex` is meant mostly for helpful or paper-specific packages and macros (in the provided example, it's for only commenting macros), I think it would be better if `xcolor` were included inside `cvpr.sty`. That way, users can use the `cvpr.sty` template with its recommended `hyperref` settings, without needing to include the `preamble.tex` file or load `xcolor` separately.

**Comment by taiya** [comment]
If you have a pull request to implement these changes, feel free to send it.
