### ISSUE TITLE
The `cite' package should not be used with natbib

### ISSUE THREAD

**Issue by tmensink** [cvpr-org/author-kit#23]
In the current cvpr.sty file, both the `cite` aswell as the `natbib` package are loaded:
```
\RequirePackage{cite}     % Automatically ordered citations
\RequirePackage[numbers,sort&compress]{natbib}
```

That yields a Latex error / warning: 
`Package natbib Warning: The 'cite' package should not be used with natbib. Use option 'sort' instead.`

Is it safe to comment out the `cite` package?

**Comment by cr333** [comment]
It is safe to comment out the `cite` package.

In fact, we removed already removed it in #8.
