### ISSUE TITLE
How to add two column figure on the first page?

### ISSUE THREAD

**Issue by ImmortalSdm** [cvpr-org/author-kit#25]
I want to add my motivation figure above the abstract, how to make it?

**Comment by taiya** [comment]
Replace `\maketitle` with:

```
\twocolumn[{%
\renewcommand\twocolumn[1][]{#1}%
\maketitle
\includegraphics[width=\linewidth]{fig/teaser.png}
\captionof{figure}{....
\vspace{2em}}
\label{fig:teaser}
}]
```

**Comment by shakesBeardZ** [comment]
@ImmortalSdm thanks for your help

**Comment by MinJunKang** [comment]
Hello, when I use this, I face the error using "\maketitlesupplementary" command. I think this error is related to twocolumn.. How can I solve this error?

**Comment by taiya** [comment]
Min, with the information provided (nothing, no way to reproduce it?),
there's not much that we can do to help
