### ISSUE TITLE
\bibliography{} starting from any number

### ISSUE THREAD

**Issue by taestaes** [cvpr-org/author-kit#28]
I'm trying to change biblography number for supplementary material.

I'm following [this](https://tex.stackexchange.com/questions/289457/bibliography-starting-from-any-number), but found out that the \usepackage[review]{cvpr} does not allow the biblography number changed.

How can I change it with cvpr package..?

**Comment by taestaes** [comment]
This may be related to https://github.com/cvpr-org/author-kit/pull/10

**Comment by taiya** [comment]
` not allow the biblography number changed` not sure I understand what you mean... Change what?

If you are asking about adding citations to the supplementary... it's fairly atypical to add new citations.
I would advise you to just add `\begin{itemize}` at the end of the supplementary, and then integrate it during camera ready/ arXiv with the primary biblio.

Indeed, split biblios are not possible with bibtex, and we'd need to upgrade the system to use biblatex (not done yet, maybe next year).

**Comment by taestaes** [comment]
> ` not allow the biblography number changed` not sure I understand what you mean... Change what?
> 
> If you are asking about adding citations to the supplementary... it's fairly atypical to add new citations. I would advise you to just add `\begin{itemize}` at the end of the supplementary, and then integrate it during camera ready/ arXiv with the primary biblio.
> 
> Indeed, split biblios are not possible with bibtex, and we'd need to upgrade the system to use biblatex (not done yet, maybe next year).

Yes, I'm adding citations: I made new tex file for supplementary material. (I don't know how to split supp with main pdf)

Thank you for your advise.

**Comment by adinriv** [comment]
It is not a problem with the template nor related to it.  It is how `bibtex` typesets the bibliography.

There are some packages that allow you to do split bibliographies with `bibtex`, see for example: https://tex.stackexchange.com/questions/44589/how-to-split-bibliography-for-different-sections.  An easier solution is to use `biblatex`, which is the modern solution to manage and handle bibliographies, but that is not in used in this template.

**Comment by taestaes** [comment]
> It is not a problem with the template nor related to it. It is how `bibtex` typesets the bibliography.
> 
> There are some packages that allow you to do split bibliographies with `bibtex`, see for example: https://tex.stackexchange.com/questions/44589/how-to-split-bibliography-for-different-sections. An easier solution is to use `biblatex`, which is the modern solution to manage and handle bibliographies, but that is not in used in this template.

Thank you. Following this, I could change the reference number!
