### ISSUE TITLE
position of line numbers error.

### ISSUE THREAD

**Issue by order-a-lemonade** [cvpr-org/author-kit#29]
![image](https://github.com/cvpr-org/author-kit/assets/66902842/2a6d2306-d496-4298-9680-58d73b9e1821)
why is the position of line numbers changed?(746 747 748 749 should be at left).
and i find this situation only appears at the bottom of page.

**Comment by cr333** [comment]
This can sometimes happen after major layout changes, e.g. figures or tables moving from one page to another.

It usually goes away when re-running LaTeX a few times, as the line numbers usually lag behind the main document by a LaTeX build cycle.

Can you please try building your document a few times to see if this goes away?

If not, can you please submit (a suitably anonymised) minimum working example that reproduces this issue?

**Comment by order-a-lemonade** [comment]
> This can sometimes happen after major layout changes, e.g. figures or tables moving from one page to another.
> 
> It usually goes away when re-running LaTeX a few times, as the line numbers usually lag behind the main document by a LaTeX build cycle.
> 
> Can you please try building your document a few times to see if this goes away?
> 
> If not, can you please submit (a suitably anonymised) minimum working example that reproduces this issue?

thanks a lot. Sometimes it did works.
For me，there is a solution:
    step1. delete section 1-6 (7 sections in total) 
    step2. re-build the latex project
    step3. add  section 1-6 back
    step4. re-build the latex project
