### ISSUE TITLE
Text not centered on page

### ISSUE THREAD

**Issue by sroth-visinf** [cvpr-org/author-kit#31]
While preparing the rebuttal template for ECCV, I discovered that recent (and not so recent) CVPR templates do not properly center the text on the page. Interestingly, this is an issue that seems to have persisted for many years. Even papers from as far back as CVPR 2014 seem to exhibit this issue (see, e.g., [this example](https://openaccess.thecvf.com/content_cvpr_2014/papers/Ponce_Trinocular_Geometry_Revisited_2014_CVPR_paper.pdf)). As can be clearly seen, the margin is bigger on the right than it is on the left. In 2013, everything was still fine (see, e.g., [here](https://openaccess.thecvf.com/content_cvpr_2013/papers/Kim_Deformable_Spatial_Pyramid_2013_CVPR_paper.pdf)).

I had a closer look at the margin specifications in the template and it seems that the calculation is off. In the current template the margin is set as:
```
\setlength{\oddsidemargin}{-.304in}
\setlength{\evensidemargin}{-.304in}
```

However, the text is 6 7/8 inches wide (official width) on a 8 1/2 inch sheet. This leaves 13/8 inches for both margins, making a 13/16 inch margin on each side. Given the 1 inch default margin of LaTeX, this means that the margins should be set as:
```
\setlength{\oddsidemargin}{-.1875in}
\setlength{\evensidemargin}{-.1875in}
```

And indeed, if I do that, everything looks nice and centered.

It would be great if someone could verify this observation and my margin calculation. If this checks out, I am happy to submit a pull request to address this issue in future conferences (or even in the CVPR 2024 camera readys).

**Comment by taiya** [comment]
I checked my own submissions and indeed text is not centered.
Should we contacted the person that modified the template in 2014 and ask if there was a reason?

**Comment by sroth-visinf** [comment]
Actually, it seems like in 2013 the template was already not centered (not sure why the final versions on the CVF webpage are centered). I still have some of my really old repos and it turns out that in 2005 this issue already existed, at least for the camera ready. The submission version still had the correct margins (-0.1875in), but did not yet use the (then presumably new) cvpr.sty style. This seems to have been introduced only for the camera ready.

Given that it has been almost 20 years, I am not sure we will succeed in figuring out why this change happened. Either we leave it be since no one seemingly noticed for so long, or we silently fix it ☺️

**Comment by taiya** [comment]
Ack.
We should probably check with IEEE whether this was done with purpose (I doubt).
The other changes I had them approved first.

**Comment by cr333** [comment]
@sroth-visinf, I can confirm that your margin calculation seems correct and will merge this in a moment. Thank you so much for this!
