### ISSUE TITLE
Re-enumeration of the references in the rebuttal

### ISSUE THREAD

**Issue by pchizhov** [cvpr-org/author-kit#33]
Hi,

It seems that the commented code for changing the index of the first reference in the rebuttal.tex has no effect:

https://github.com/cvpr-org/author-kit/blob/main/rebuttal.tex#L36-L41

The references are still starting from 1. The piece of code seems correct in general, but it is somehow ignored because of something in the .sty or .bst files.

**Comment by cr333** [comment]
Thanks for pointing this out. I just posted a fix in PR #34. Hope this helps.

**Comment by pchizhov** [comment]
@cr333 works now, thank you very much!

**Comment by cr333** [comment]
PR #34 fixing this issue has now been merged into main.
