### ISSUE TITLE
can we have a typst template?

### ISSUE THREAD

**Issue by NeutrinoLiu** [cvpr-org/author-kit#46]
is there any plan to provide a template for typst (https://github.com/typst/typst) ?
a modern alternative for latex.

**Comment by cr333** [comment]
There is currently no plan for this as the vast majority of papers are authored using LaTeX.

However, please feel free to use whatever typesetting tool you prefer, as long as the produced document is consistent with the official paper template in `main.tex`.

**Comment by taiya** [comment]
@drebain – there is some hunger for it, it seems.

**Comment by drebain** [comment]
I had looked into it and got most of the way through putting a typst template together. The main issue that stopped me was that there was a limitation of multi-column float support ( https://github.com/typst/typst/issues/553 ) that made it difficult to support full width figures and tables. However, this seems to have been fixed two weeks ago so I might revisit it.

**Comment by NeutrinoLiu** [comment]
resolved: https://typst.app/universe/package/blind-cvpr
