### ISSUE TITLE
Appendix sections referred differently than main paper section

### ISSUE THREAD

**Issue by jmlipman** [cvpr-org/author-kit#47]
Hi,

I'm not sure if this is a "it's not a bug it's a feature" case, but I noticed that sections in the main body of the paper and the sections in the Appendix/supplementary material are named and referred to similarly. So, when reading the paper, it's not clear if the sections belong to paper or to the appendix. Also, their number is the number after the conclusion, i.e., if conclusion is Section 6, then, "Appendix A" would be "Section 7".

**Comment by cr333** [comment]
You could also use the code here to continue the numbering of sections, figures and equations in the (separate) supplement from the main paper:
https://github.com/cvpr-org/author-kit/blob/1ce836777851be0386e3d3868e9cc6b3ca8b4d48/rebuttal.tex#L19-L24
