### ISSUE TITLE
Something is wrong with [pagenumbers] settings in Overleaf so that compilation fails

### ISSUE THREAD

**Issue by Y-Z-Chen** [cvpr-org/author-kit#49]
A series of control consequences beginning with `\@LN` are shown as undefined.

**Comment by taiya** [comment]
![image](https://github.com/user-attachments/assets/2f177c59-60ce-4212-a27c-d1f0babb99ad)
My students just check @cr333 – and it seems this happens when this option is used?

**Comment by taiya** [comment]
@Y-Z-Chen seems re-compiling from scratch fixes the issue?
![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/fee5f614-9110-46a6-93b8-354262a60c09)

**Comment by cr333** [comment]
That's a good catch of the issue and how to work around it!

I found a solution [here](https://tex.stackexchange.com/a/125779) and verified that it fixes this issue on Overleaf. Please see PR #50 for the fix.
